=== service-oriented-science/Globus-Security/main/src/main/resources/org/globus/crux/crux-jetty.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>


<xs:schema xmlns="http://www.globus.org/crux/jsse-config"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:beans="http://www.springframework.org/schema/beans"
	xmlns:tool="http://www.springframework.org/schema/tool"
	targetNamespace="http://www.globus.org/crux/jsse-config" xmlns:tns="http://www.globus.org/crux/jsse-config"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0">

	<xs:import namespace="http://www.springframework.org/schema/beans" />

	<xs:element name="server" type="serverType" />

	<xs:complexType name="serverType">
		<xs:complexContent>
			<xs:extension base="beans:identifiedType">

				<xs:sequence>
					<xs:element type="threadPoolType" name="threadPool"
						minOccurs="0" maxOccurs="1" />

					<xs:element name="connectors" minOccurs="0" maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:choice minOccurs="1" maxOccurs="unbounded">
									<xs:element type="nonBlockingConnectorType"
										name="nonBlockingConnector" />
									<xs:element type="sslConnectorType" name="sslConnector" />
									<xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" />
								</xs:choice>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="jksTrustManagerType">
		<xs:sequence>
			<xs:element name="keyStore" type="xs:string" />
			<xs:element name="keyStorePassword" type="xs:string" />
			<xs:element name="keyPassword" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="trustStore" type="xs:string" />
			<xs:element name="trustStorePassword" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="trustManagerType">
		<xs:choice minOccurs="1" maxOccurs="1">
			<xs:element name="jks" type="jksTrustManagerType" />
			<xs:element name="gsi" type="gsiTrustManagerType" />
			<xs:any namespace="##other" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="keyCertType">

	</xs:complexType>

	<xs:complexType name="credentialType">
		<xs:choice>
			<xs:element name="proxyCredentialLocation" type="xs:string" />
			<xs:sequence>
				<xs:element name="keyLocation" type="xs:string" />
				<xs:element name="certificateLocation" type="xs:string" />
			</xs:sequence>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="gsiTrustManagerType">
		<xs:sequence>
			<xs:element name="trustedCertLocations" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="credential" type="credentialType"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="crlLocations" type="xs:string"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="signingPolicyLocations" type="xs:string"
				minOccurs="0" maxOccurs="1" />

		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="sslConnectorType">
		<xs:complexContent>
			<xs:extension base="connectorType">
				<xs:sequence>
					<xs:element name="trustManager" type="trustManagerType"
						minOccurs="1" maxOccurs="1" />
				</xs:sequence>
				<xs:attribute name="requireClientAuthn" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="connectorType">
		<xs:attribute name="port" type="xs:int" />
		<xs:attribute name="host" type="xs:string" />
		<xs:attribute name="timeout" type="xs:int" />
		<xs:attribute name="protocol" type="xs:string" />
		<xs:attribute name="bufferSize" type="xs:int" />
	</xs:complexType>

	<xs:attributeGroup name="connectorAttributes">

	</xs:attributeGroup>

	<xs:complexType name="nonBlockingConnectorType">
		<xs:complexContent>
			<xs:extension base="connectorType" />
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="threadPoolType">
		<xs:attribute name="class" use="optional" type="xs:string" />
		<xs:attribute name="minSize" use="optional" type="xs:int" />
		<xs:attribute name="maxSize" use="optional" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="insecureConnectorType">
		<xs:attributeGroup ref="connectorAttributes" />

	</xs:complexType>


</xs:schema>

=== service-oriented-science/Globus-Security/main/src/test/resources/context.xml
<?xml version="1.0" encoding="UTF-8"?>
<server id="jetty" xmlns="http://www.globus.org/crux/jetty-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.globus.org/crux/jetty-config 
	file:///${user.dir}/target/classes/org/globus/crux/crux-jetty.xsd
	http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

	<threadPool minSize="10" maxSize="20" />

	<connectors>
		<sslConnector port="12345" requireClientAuthn="true">
			<trustManager>
				<gsi>
					<trustedCertLocations>file:///${user.dir}/src/test/resources/cacert.pem
					</trustedCertLocations>
					<credential>
						<keyLocation>file:///${user.dir}/src/test/resources/userkey.pem
						</keyLocation>
						<certificateLocation>file:///${user.dir}/src/test/resources/usercert.pem
						</certificateLocation>
					</credential>
					<crlLocations>file:///${user.dir}/src/test/resources/1c3f2ca8.r0
					</crlLocations>
					<signingPolicyLocations>file:///${user.dir}/src/test/resources/globus_crux_ca.signing_policy</signingPolicyLocations>
				</gsi>
			</trustManager>
		</sslConnector>
	</connectors>
</server>
